from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet, WeatherAPIView
"""
This module contains the URL configuration for the API v1 of the ToDo application.

The `router` is an instance of `DefaultRouter` from the `rest_framework.routers` module.
It is used to automatically generate the URL patterns for the registered viewsets.

The `TaskViewSet` is a custom viewset defined in the `views.py` module.
It is responsible for handling CRUD operations for the Task model.

The `urlpatterns` variable is a list of URL patterns generated by the `router`.
These patterns are used to map URLs to the corresponding viewsets.

The `app_name` variable is used to namespace the URLs within the ToDo application.
"""

from django.views.decorators.cache import cache_page


app_name = "api-v1"

router = DefaultRouter()
router.register("task", TaskViewSet, basename="task")
urlpatterns = router.urls
urlpatterns += [
    path('api/weather/<str:city_name>/', WeatherAPIView.as_view(), name='weather'),

]
