name: Test in staging environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: name
        ports:
          - 5432:5432
        volumes:
          - postgres_data:/var/lib/postgresql/data

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Up project
        run: docker-compose -f docker-compose-stage.yml up -d

      - name: Run pytest
        run: docker-compose exec -T backend sh -c "pytest ."

